/**
 * ============================================================
 * MULTI-TENANT DATABASE — src/db/multiTenantDB.js
 * ============================================================
 * ARCHITECTURE OVERVIEW
 * ─────────────────────
 * This is a NATIONAL SYSTEM. Every village in Uganda uses the
 * same web application but each village's data is completely
 * isolated in its own IndexedDB database:
 *
 *   lc1-master          — System admin DB (one per device)
 *   lc1-village-{id}    — One DB per village (e.g. lc1-village-V024)
 *
 * HOW IT WORKS:
 *   1. On login, the user selects their village.
 *   2. We open the DB named `lc1-village-{villageId}`.
 *   3. ALL reads/writes for that session go to that DB only.
 *   4. A SYSTEM_ADMIN (master) account can open ANY village's DB
 *      for maintenance, password resets, and cross-village checks.
 *
 * CROSS-VILLAGE NIN CHECK:
 *   When registering a resident, we check their NIN against:
 *     a) The current village DB (local, always)
 *     b) All other village DBs on this device (local, best-effort)
 *     c) The central API server (if online)
 *   This prevents a person being registered as an active resident
 *   in two villages simultaneously.
 *
 * RESIDENT STATUS RULES:
 *   - 'active'   → counted in "current residents" stat
 *   - 'deceased' → moved to deceased section, NOT counted in active
 *   - 'migrated' → moved out, NOT counted in active, can register
 *                  as active in a new village
 *   - 'tenant'   → registered here but "home village" is elsewhere
 *                  (NIN can appear active in their home village too)
 *
 * BIRTH → RESIDENT AUTO-CREATION:
 *   When a birth is registered, a new resident record is auto-created
 *   with status='active', incrementing the active resident count.
 * ============================================================
 */

import { openDB } from 'idb'
import { hashPassword } from '../security/crypto.js'

// ── Database name builders ─────────────────────────────────────────────────
const MASTER_DB_NAME  = 'lc1-master'          // system admin + village registry
const villageDBName   = (id) => `lc1-village-${id}`  // per-village data

const DB_VERSION = 1

// ─────────────────────────────────────────────────────────────────────────
// MASTER DATABASE (system admin, village registry, password resets)
// ─────────────────────────────────────────────────────────────────────────

/**
 * getMasterDB()
 * Opens the master database used by the SYSTEM_ADMIN account.
 * Contains: system users, all registered villages, reset tokens, global audit.
 */
export async function getMasterDB() {
  return openDB(MASTER_DB_NAME, DB_VERSION, {
    upgrade(db) {

      // ── SYSTEM USERS ─────────────────────────────────────────────────
      // Stores the master admin account and any super-users.
      if (!db.objectStoreNames.contains('systemUsers')) {
        const u = db.createObjectStore('systemUsers', { keyPath: 'id' })
        u.createIndex('username',   'username',   { unique: true })
        u.createIndex('role',       'role')
      }

      // ── VILLAGE REGISTRY ──────────────────────────────────────────────
      // One record per village that has been set up on this device.
      // Lets us list all villages for the master admin and for cross-village NIN checks.
      if (!db.objectStoreNames.contains('villageRegistry')) {
        const v = db.createObjectStore('villageRegistry', { keyPath: 'villageId' })
        v.createIndex('districtId', 'districtId')
        v.createIndex('setupAt',    'setupAt')
      }

      // ── PASSWORD RESET TOKENS ─────────────────────────────────────────
      // Short-lived tokens generated by master admin for village officials.
      // Token expires after 24 hours.
      if (!db.objectStoreNames.contains('resetTokens')) {
        const t = db.createObjectStore('resetTokens', { keyPath: 'token' })
        t.createIndex('villageId', 'villageId')
        t.createIndex('username',  'username')
        t.createIndex('expiresAt', 'expiresAt')
      }

      // ── GLOBAL AUDIT ──────────────────────────────────────────────────
      // Cross-village operations logged here (password resets, village setups).
      if (!db.objectStoreNames.contains('globalAudit')) {
        const a = db.createObjectStore('globalAudit', { keyPath: 'id', autoIncrement: true })
        a.createIndex('villageId', 'villageId')
        a.createIndex('action',    'action')
        a.createIndex('timestamp', 'timestamp')
      }
    }
  })
}

// ─────────────────────────────────────────────────────────────────────────
// VILLAGE DATABASE
// ─────────────────────────────────────────────────────────────────────────

/**
 * getVillageDB(villageId)
 * Opens (or creates) the IndexedDB for a specific village.
 * All session data reads/writes go through this.
 *
 * @param {string} villageId - e.g. 'V024' from ugandaLocations.js
 */
export async function getVillageDB(villageId) {
  if (!villageId) throw new Error('villageId is required to open a village database')

  return openDB(villageDBName(villageId), DB_VERSION, {
    upgrade(db) {

      // ── RESIDENTS ────────────────────────────────────────────────────
      // status: 'active' | 'deceased' | 'migrated' | 'tenant'
      // 'active'   — permanent resident, counted in active count
      // 'deceased' — died here, kept for records, NOT in active count
      // 'migrated' — left the village, NOT in active count, frees NIN for new village
      // 'tenant'   — lives here but home is elsewhere, counted in active (of this village)
      if (!db.objectStoreNames.contains('residents')) {
        const r = db.createObjectStore('residents', { keyPath: 'id' })
        r.createIndex('nin',        'nin',        { unique: false }) // not unique here because tenants may appear in 2 villages
        r.createIndex('ninActive',  ['nin','status'])               // composite: for cross-village unique-active check
        r.createIndex('surname',    'surname')
        r.createIndex('status',     'status')
        r.createIndex('createdAt',  'createdAt')
        r.createIndex('syncStatus', 'syncStatus')
        r.createIndex('residentType','residentType') // 'permanent' | 'tenant'
      }

      // ── HOUSEHOLDS ───────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('households')) {
        const h = db.createObjectStore('households', { keyPath: 'id' })
        h.createIndex('headId',    'headId')
        h.createIndex('syncStatus','syncStatus')
      }

      // ── LAND ─────────────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('land')) {
        const l = db.createObjectStore('land', { keyPath: 'id' })
        l.createIndex('ownerId',    'ownerId')
        l.createIndex('plotNumber', 'plotNumber')
        l.createIndex('syncStatus', 'syncStatus')
      }

      // ── CASES ────────────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('cases')) {
        const c = db.createObjectStore('cases', { keyPath: 'id' })
        c.createIndex('status',        'status')
        c.createIndex('category',      'category')
        c.createIndex('complainantId', 'complainantId')
        c.createIndex('syncStatus',    'syncStatus')
      }

      // ── MEETINGS ─────────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('meetings')) {
        const m = db.createObjectStore('meetings', { keyPath: 'id' })
        m.createIndex('date',      'date')
        m.createIndex('syncStatus','syncStatus')
      }

      // ── BIRTHS ───────────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('births')) {
        const b = db.createObjectStore('births', { keyPath: 'id' })
        b.createIndex('childName',  'childName')
        b.createIndex('motherId',   'motherId')
        b.createIndex('dateOfBirth','dateOfBirth')
        b.createIndex('syncStatus', 'syncStatus')
        b.createIndex('residentCreated', 'residentCreated') // true once auto-resident created
      }

      // ── DEATHS ───────────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('deaths')) {
        const d = db.createObjectStore('deaths', { keyPath: 'id' })
        d.createIndex('residentId', 'residentId')
        d.createIndex('dateOfDeath','dateOfDeath')
        d.createIndex('syncStatus', 'syncStatus')
      }

      // ── LETTERS ──────────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('letters')) {
        const lt = db.createObjectStore('letters', { keyPath: 'id' })
        lt.createIndex('residentId','residentId')
        lt.createIndex('type',      'type')
        lt.createIndex('issuedAt',  'issuedAt')
        lt.createIndex('syncStatus','syncStatus')
      }

      // ── WELFARE ──────────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('welfare')) {
        const w = db.createObjectStore('welfare', { keyPath: 'id' })
        w.createIndex('residentId', 'residentId')
        w.createIndex('programType','programType')
        w.createIndex('status',     'status')
        w.createIndex('syncStatus', 'syncStatus')
      }

      // ── BUSINESSES ───────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('businesses')) {
        const bz = db.createObjectStore('businesses', { keyPath: 'id' })
        bz.createIndex('ownerId',  'ownerId')
        bz.createIndex('type',     'type')
        bz.createIndex('status',   'status')
        bz.createIndex('syncStatus','syncStatus')
      }

      // ── SECURITY ─────────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('security')) {
        const s = db.createObjectStore('security', { keyPath: 'id' })
        s.createIndex('date',      'date')
        s.createIndex('type',      'type')
        s.createIndex('status',    'status')
        s.createIndex('syncStatus','syncStatus')
      }

      // ── USERS (LC1 committee for this village) ────────────────────────
      if (!db.objectStoreNames.contains('users')) {
        const u = db.createObjectStore('users', { keyPath: 'id' })
        u.createIndex('username',  'username',  { unique: true })
        u.createIndex('role',      'role')
        u.createIndex('userStatus','userStatus')
      }

      // ── AUDIT LOG ────────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('audit')) {
        const a = db.createObjectStore('audit', { keyPath: 'id', autoIncrement: true })
        a.createIndex('table',    'table')
        a.createIndex('userId',   'userId')
        a.createIndex('action',   'action')
        a.createIndex('timestamp','timestamp')
      }

      // ── SETTINGS ─────────────────────────────────────────────────────
      if (!db.objectStoreNames.contains('settings')) {
        db.createObjectStore('settings', { keyPath: 'key' })
      }

      // ── VILLAGE PROFILE ───────────────────────────────────────────────
      if (!db.objectStoreNames.contains('villageProfile')) {
        db.createObjectStore('villageProfile', { keyPath: 'key' })
      }
    }
  })
}

// ─────────────────────────────────────────────────────────────────────────
// BOOTSTRAP — MASTER ADMIN + VILLAGE FIRST-RUN SETUP
// ─────────────────────────────────────────────────────────────────────────

/**
 * seedMasterAdmin()
 * Creates the master SYSTEM_ADMIN account on first launch.
 * This account can log into any village for maintenance.
 */
export async function seedMasterAdmin() {
  const db    = await getMasterDB()
  const count = await db.count('systemUsers')
  if (count === 0) {
    // Hash the default password before storing
    const hashedPw = await hashPassword('MoLG@Uganda2024')
    await db.add('systemUsers', {
      id:         'master-001',
      username:   'sysadmin',
      password:   hashedPw,   // stored as PBKDF2 hash, never plain text
      role:       'SYSTEM_ADMIN',
      fullName:   'System Administrator',
      userStatus: 'active',
      createdAt:  new Date().toISOString()
    })
  }
}

/**
 * setupVillage(villageProfile)
 * Called when a village is set up for the first time on a device.
 * Creates their Chairperson account and registers the village in the master registry.
 *
 * @param {object} villageProfile - { villageId, villageName, ... }
 * @param {object} chairAccount   - { username, password, fullName }
 */
export async function setupVillage(villageProfile, chairAccount) {
  const masterDB  = await getMasterDB()
  const villageDB = await getVillageDB(villageProfile.villageId)

  // Check if this village already has users — if so, it's already set up
  const existingUsers = await villageDB.count('users')
  if (existingUsers > 0) {
    // Village already set up — do NOT overwrite credentials.
    // Return alreadyExisted flag so the UI can show the right message
    // instead of trying to log in with potentially wrong credentials.
    return { alreadyExisted: true }
  }

  // Register in master village registry (upsert — safe to repeat)
  await masterDB.put('villageRegistry', {
    ...villageProfile,
    setupAt:  new Date().toISOString(),
    isActive: true,
  })

  // Hash password before storing — never store plain text
  const hashedChairPw = await hashPassword(chairAccount.password)
  await villageDB.add('users', {
    id:         `chair-${villageProfile.villageId}`,
    username:   chairAccount.username,
    password:   hashedChairPw,
    role:       'LC1_CHAIR',
    fullName:   chairAccount.fullName,
    userStatus: 'active',
    phone:      chairAccount.phone || '',
    createdAt:  new Date().toISOString()
  })

  // Save the village profile in the village DB settings
  for (const [key, value] of Object.entries(villageProfile)) {
    await villageDB.put('settings', { key, value })
    await villageDB.put('villageProfile', { key, value })
  }

  // Log to global audit
  await masterDB.add('globalAudit', {
    action:    'VILLAGE_SETUP',
    villageId: villageProfile.villageId,
    details:   { villageName: villageProfile.villageName },
    timestamp: new Date().toISOString()
  })

  return { alreadyExisted: false }
}

/**
 * isVillageSetup(villageId)
 * Returns true if this village has already been configured on this device.
 */
export async function isVillageSetup(villageId) {
  try {
    const db  = await getMasterDB()
    const rec = await db.get('villageRegistry', villageId)
    return !!rec
  } catch { return false }
}

/**
 * getRegisteredVillages()
 * Returns all villages set up on this device — used by master admin.
 */
export async function getRegisteredVillages() {
  const db = await getMasterDB()
  return db.getAll('villageRegistry')
}

// ─────────────────────────────────────────────────────────────────────────
// CROSS-VILLAGE NIN UNIQUENESS CHECK
// ─────────────────────────────────────────────────────────────────────────

/**
 * checkNINAcrossVillages(nin, currentVillageId, excludeResidentId)
 * Checks whether a NIN is already registered in any OTHER village.
 *
 * DECEASED RULE: A deceased person's NIN is PERMANENTLY BLOCKED.
 * Their identity cannot be reused under any circumstances — not as
 * a tenant, not as affiliated, not for any registration reason.
 * This prevents identity fraud using deceased persons' documents.
 *
 * Returns:
 *   { conflict: false }
 *   { conflict: true, villages: [...], deceased: true/false }
 */
export async function checkNINAcrossVillages(nin, currentVillageId, excludeResidentId = null) {
  if (!nin || nin.length < 5) return { conflict: false }

  const villages  = await getRegisteredVillages()
  const conflicts = []

  for (const village of villages) {
    if (village.villageId === currentVillageId) continue
    try {
      const db  = await getVillageDB(village.villageId)
      const all = await db.getAll('residents')
      const found = all.filter(r =>
        r.id !== excludeResidentId &&
        r.nin === nin &&
        // Block if: active, affiliated, migrated, OR deceased
        // Only exclude if explicitly never registered (shouldn't exist if nin matches)
        r.status !== undefined
      )
      if (found.length > 0) {
        conflicts.push({
          villageId:   village.villageId,
          villageName: village.villageName,
          resident:    found[0],
          deceased:    found[0].status === 'deceased',
        })
      }
    } catch { /* village DB not on this device */ }
  }

  return conflicts.length > 0
    ? { conflict: true, villages: conflicts, deceased: conflicts.some(c => c.deceased) }
    : { conflict: false }
}

/**
 * checkNameDOBAcrossVillages(surname, firstName, dateOfBirth, currentVillageId, excludeId)
 * Checks whether a person with the same surname + firstName + dateOfBirth
 * already exists in ANY village on this device.
 *
 * DECEASED RULE: If the matching person is deceased, this is a HARD BLOCK.
 * A deceased person's name and date of birth cannot be registered again
 * regardless of registration reason.
 *
 * Returns:
 *   { conflict: false }
 *   { conflict: true, villages: [...], deceased: true/false }
 */
export async function checkNameDOBAcrossVillages(
  surname, firstName, dateOfBirth, currentVillageId, excludeId = null
) {
  if (!surname || !firstName || !dateOfBirth) return { conflict: false }

  const villages  = await getRegisteredVillages()
  const conflicts = []
  const sl = surname.trim().toLowerCase()
  const fl = firstName.trim().toLowerCase()

  for (const village of villages) {
    if (village.villageId === currentVillageId) continue
    try {
      const db  = await getVillageDB(village.villageId)
      const all = await db.getAll('residents')
      const found = all.filter(r =>
        r.id !== excludeId &&
        r.surname?.trim().toLowerCase()   === sl &&
        r.firstName?.trim().toLowerCase() === fl &&
        r.dateOfBirth === dateOfBirth
        // No status filter — deceased records also block re-registration
      )
      if (found.length > 0) {
        conflicts.push({
          villageId:   village.villageId,
          villageName: village.villageName,
          resident:    found[0],
          deceased:    found[0].status === 'deceased',
        })
      }
    } catch { /* village DB not on this device */ }
  }

  return conflicts.length > 0
    ? { conflict: true, villages: conflicts, deceased: conflicts.some(c => c.deceased) }
    : { conflict: false }
}

// ─────────────────────────────────────────────────────────────────────────
// PASSWORD RESET TOKENS
// ─────────────────────────────────────────────────────────────────────────

/**
 * generateResetToken(villageId, username)
 * Master admin generates a one-time reset token for a village official.
 * Token expires in 24 hours. Returns the token string to give to the user.
 */
export async function generateResetToken(villageId, username) {
  const db    = await getMasterDB()
  // Generate a random 8-character token (easy to type/communicate verbally)
  const token = Math.random().toString(36).slice(2, 10).toUpperCase()
  const expiry = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString()

  await db.put('resetTokens', {
    token,
    villageId,
    username,
    expiresAt: expiry,
    used:      false,
    createdAt: new Date().toISOString()
  })

  await db.add('globalAudit', {
    action: 'RESET_TOKEN_GENERATED',
    villageId,
    details: { username, token, expiresAt: expiry },
    timestamp: new Date().toISOString()
  })

  return token
}

/**
 * verifyAndUseResetToken(token, villageId, username)
 * Validates a reset token. Returns true if valid, false otherwise.
 * Marks the token as used so it cannot be reused.
 */
export async function verifyAndUseResetToken(token, villageId, username) {
  const db  = await getMasterDB()
  const rec = await db.get('resetTokens', token)

  if (!rec)                             return { valid: false, reason: 'Token not found' }
  if (rec.used)                         return { valid: false, reason: 'Token already used' }
  if (rec.villageId !== villageId)      return { valid: false, reason: 'Wrong village' }
  if (rec.username !== username)        return { valid: false, reason: 'Wrong username' }
  if (new Date(rec.expiresAt) < new Date()) return { valid: false, reason: 'Token expired' }

  // Mark as used
  await db.put('resetTokens', { ...rec, used: true, usedAt: new Date().toISOString() })
  return { valid: true }
}

/**
 * resetUserPassword(villageId, username, newPassword)
 * Sets a new password for a village official after token verification.
 */
export async function resetUserPassword(villageId, username, newPassword) {
  const db     = await getVillageDB(villageId)
  const user   = await db.getFromIndex('users', 'username', username)
  if (!user) throw new Error('User not found in this village')
  const hashed = await hashPassword(newPassword)   // always hash before storing
  await db.put('users', { ...user, password: hashed, updatedAt: new Date().toISOString() })
}

// ─────────────────────────────────────────────────────────────────────────
// RESIDENT POPULATION STATS (live counts)
// ─────────────────────────────────────────────────────────────────────────

/**
 * getResidentStats(villageId)
 * Returns accurate population counts split by status.
 * This is the source of truth for the dashboard stat tiles.
 *
 * RULES:
 *   activeCount   = residents WHERE status IN ('active', 'tenant')
 *   deceasedCount = residents WHERE status = 'deceased'
 *   migratedCount = residents WHERE status = 'migrated'
 */
export async function getResidentStats(villageId) {
  const db        = await getVillageDB(villageId)
  const all       = await db.getAll('residents')
  const active    = all.filter(r => r.status === 'active' || r.status === 'tenant')
  const deceased  = all.filter(r => r.status === 'deceased')
  const migrated  = all.filter(r => r.status === 'migrated')
  return {
    total:    all.length,
    active:   active.length,
    deceased: deceased.length,
    migrated: migrated.length,
    tenants:  all.filter(r => r.residentType === 'tenant').length,
    male:     active.filter(r => r.sex === 'Male').length,
    female:   active.filter(r => r.sex === 'Female').length,
  }
}

/**
 * getDashboardStats(villageId)
 * Returns all headline counts for the dashboard.
 */
export async function getDashboardStats(villageId) {
  const db = await getVillageDB(villageId)
  const [households, land, births, deaths, welfare, businesses, security] =
    await Promise.all([
      db.count('households'), db.count('land'),
      db.count('births'),     db.count('deaths'),
      db.count('welfare'),    db.count('businesses'), db.count('security'),
    ])
  const allCases  = await db.getAll('cases')
  const openCases = allCases.filter(c => c.status === 'open').length
  const resStats  = await getResidentStats(villageId)

  return {
    ...resStats,
    residents: resStats.active,  // dashboard "residents" = active only
    households, land, births, deaths,
    cases: allCases.length, openCases,
    welfare, businesses, security,
  }
}

// ─────────────────────────────────────────────────────────────────────────
// GENERIC CRUD HELPERS (village-scoped)
// ─────────────────────────────────────────────────────────────────────────

export async function vdbAdd(villageId, store, record) {
  const db = await getVillageDB(villageId)
  return db.add(store, { ...record, syncStatus:'pending', updatedAt: new Date().toISOString() })
}

export async function vdbPut(villageId, store, record) {
  const db = await getVillageDB(villageId)
  return db.put(store, { ...record, syncStatus:'pending', updatedAt: new Date().toISOString() })
}

export async function vdbGet(villageId, store, id) {
  const db = await getVillageDB(villageId)
  return db.get(store, id)
}

export async function vdbGetAll(villageId, store) {
  const db = await getVillageDB(villageId)
  return db.getAll(store)
}

export async function vdbGetByIndex(villageId, store, index, value) {
  const db = await getVillageDB(villageId)
  return db.getAllFromIndex(store, index, value)
}

export async function vdbDelete(villageId, store, id) {
  const db = await getVillageDB(villageId)
  return db.delete(store, id)
}

export async function vdbCount(villageId, store) {
  const db = await getVillageDB(villageId)
  return db.count(store)
}

export async function vdbAudit(villageId, action, table, recordId, userId, details = {}) {
  const db = await getVillageDB(villageId)
  await db.add('audit', { action, table, recordId, userId, details,
    timestamp: new Date().toISOString() })
}

// ─────────────────────────────────────────────────────────────────────────
// BIRTH → RESIDENT AUTO-CREATION
// ─────────────────────────────────────────────────────────────────────────

/**
 * createResidentFromBirth(villageId, birthRecord, userId)
 * When a birth is registered, automatically create a resident record
 * for the newborn. This increments the active resident count.
 *
 * @param {string} villageId   - current village
 * @param {object} birthRecord - the saved birth record
 * @param {string} userId      - who performed the action
 * @returns {string} id of the created resident
 */
export async function createResidentFromBirth(villageId, birthRecord, userId) {
  const { v4: uuidv4 } = await import('uuid')
  const db    = await getVillageDB(villageId)
  const now   = new Date().toISOString()
  const resId = uuidv4()

  const residentRecord = {
    id:           resId,
    // FIX: use childSurname (explicitly entered) not birth.surname (didn't exist)
    surname:      birthRecord.childSurname || '',
    firstName:    birthRecord.childName || '',
    otherNames:   '',
    dateOfBirth:  birthRecord.dateOfBirth,
    sex:          birthRecord.sex || '',
    village:      birthRecord.village || '',
    status:       'active',                             // born here = active resident
    residentType: 'permanent',
    motherId:     birthRecord.motherId || '',
    fatherId:     birthRecord.fatherId || '',
    birthId:      birthRecord.id,                       // link back to birth record
    nationality:  'Ugandan',
    createdAt:    now,
    createdBy:    userId,
    syncStatus:   'pending',
    updatedAt:    now,
    source:       'birth_registration',
  }

  await db.add('residents', residentRecord)

  // Mark birth record as having created a resident
  const birth = await db.get('births', birthRecord.id)
  if (birth) {
    await db.put('births', { ...birth, residentCreated: true, residentId: resId })
  }

  await db.add('audit', {
    action: 'CREATE', table: 'residents', recordId: resId, userId,
    details: { source: 'birth_registration', childName: birthRecord.childName },
    timestamp: now
  })

  return resId
}

// Re-export old helpers for backward compatibility with existing page files
// These read from the legacy single-DB (for pages not yet migrated)
export { getDB, dbAdd, dbPut, dbGet, dbGetAll, dbGetByIndex, dbDelete, dbCount, logAudit,
  saveVillageProfile, getVillageProfile, isRoleAvailable, getActiveRoleHolder, seedAdmin }
  from './index.js'
